name: Release Nightly Debug Win

on:
  # Allow for manual dispatch on GitHub
  workflow_dispatch:

jobs:
  create-nightly-debug-release:
    name: Create Nightly Debug Release
    runs-on: ubuntu-24.04
    outputs:
      is_active: ${{ steps.activity.outputs.is_active }}
      date: ${{ steps.current_time_underscores.outputs.formattedTime }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      package_prefix: ruffle-nightly-${{ steps.current_time_underscores.outputs.formattedTime }}
      tag_name: nightly-debug-${{ steps.current_time_dashes.outputs.formattedTime }}

    # Only run the scheduled workflows on the main repo.
    if: github.repository == 'ruffle-rs/ruffle' || github.event_name == 'repository_dispatch' || github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v4

      - name: Check for repo activity
        id: activity
        run: |
          # Skip activity check when manually triggered.
          if [ "${{ github.event_name }}" == "repository_dispatch" ] || [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            is_active=true
          elif [ "$(git rev-list --after="24 hours" ${{ github.sha }})" ]; then
            is_active=true
          else
            is_active=false
          fi
          echo "is_active=$is_active" >> $GITHUB_OUTPUT

      - name: Get current time with dashes
        uses: 1466587594/get-current-time@v2.1.2
        id: current_time_dashes
        with:
          format: YYYY-MM-DD

      - name: Get current time with underscores
        uses: 1466587594/get-current-time@v2.1.2
        id: current_time_underscores
        with:
          format: YYYY_MM_DD

      - name: Create release
        if: steps.activity.outputs.is_active == 'true'
        id: create_release
        run: |
          tag_name="nightly-debug-${{ steps.current_time_dashes.outputs.formattedTime }}"
          release_name="Nightly Debug ${{ steps.current_time_dashes.outputs.formattedTime }}"
          gh release create "$tag_name" --title "$release_name" --generate-notes --prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build ${{ matrix.build_name }}
    needs: create-nightly-debug-release
    if: needs.create-nightly-debug-release.outputs.is_active == 'true'
    strategy:
      fail-fast: false
      matrix:
        include:
          - build_name: windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            RUSTFLAGS: -Ctarget-feature=+crt-static
            DESKTOP_FEATURES: jpegxr,avm_debug
            MSI_ARCH: x64

    env:
      PACKAGE_FILE: ${{ needs.create-nightly-debug-release.outputs.package_prefix }}-${{ matrix.build_name }}.${{ startsWith(matrix.build_name, 'win') && 'zip' || 'tar.gz' }}
      CARGO_BUILD_DIR: target/${{ matrix.target }}/release

    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone Ruffle repo
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Install WiX
        run: |
          dotnet tool install --global wix
          wix extension add -g WixToolset.UI.wixext
          wix extension add -g WixToolset.Util.wixext
        if: runner.os == 'Windows'

      - name: Cargo build
        run: cargo build --locked --package ruffle_desktop --release ${{matrix.DESKTOP_FEATURES && '--features' }} ${{matrix.DESKTOP_FEATURES}} ${{ matrix.target && '--target' }} ${{ matrix.target }}
        env:
          RUSTFLAGS: ${{ matrix.RUSTFLAGS }}
          MACOSX_DEPLOYMENT_TARGET: ${{ matrix.MACOSX_DEPLOYMENT_TARGET }}

      - name: Package common
        run: |
          mkdir package
          cp README.md package/README.md
          cp LICENSE.md package/LICENSE.md

      - name: Package MSI
        run: |
          cd desktop/packages/windows/wix
          wix build ruffle.wxs -ext WixToolset.UI.wixext -ext WixToolset.Util.wixext -arch ${{ matrix.MSI_ARCH }} -o ../../../../package/setup.msi -pdbtype none
        env:
          RUFFLE_VERSION: "0.1.0"
          CARGO_BUILD_DIR: ../../../../target/${{ matrix.target }}/release
        if: runner.os == 'Windows'

      - name: Package Windows
        if: runner.os == 'Windows'
        run: |
          cp ${{ env.CARGO_BUILD_DIR }}/ruffle_desktop.exe package/ruffle.exe
          7z a ${{ env.PACKAGE_FILE }} ./package/*
        
      - name: Upload package
        if: runner.os != 'macOS'
        run: gh release upload "${{ needs.create-nightly-debug-release.outputs.tag_name }}" "${{ env.PACKAGE_FILE }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
